# Development environment for working with the Compact ID Resolution Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
version: "3.5"
services:
    postgresql:
        image: postgres
        environment:
            - POSTGRES_DB=devdatabase
            - POSTGRES_USER=devusername
            - POSTGRES_PASSWORD=devpassword
        ports:
            - "5430:5432"
        volumes:
            - "registry:/var/lib/postgresql/data"
    hqregistry:
        image: identifiersorg/cloud-hq-ws-registry
        environment:
            - HQ_WS_REGISTRY_CONFIG_JDBC_URL=jdbc:postgresql://postgresql:5432/devdatabase
            - HQ_WS_REGISTRY_CONFIG_RDBMS_USERNAME=devusername
            - HQ_WS_REGISTRY_CONFIG_RDBMS_PASSWORD=devpassword
            - HQ_WS_REGISTRY_CONFIG_APPLICATION_ACTIVE_PROFILE=development,authdisabled
        ports:
            - "8180:8180"
        depends_on:
            - postgresql
    redis:
        image: redis:4.0.8-alpine
        ports:
            - "6378:6379"
    recommender:
        image: identifiersorg/cloud-ws-resource-recommender
        environment:
            - WS_RESOURCE_RECOMMENDER_JVM_MEMORY_MAX=1024m
            - WS_RESOURCE_RECOMMENDER_CONFIG_BACKEND_SERVICE_LINK_CHECKER_HOST=link-checker
        ports:
            - "8083:8083"
        depends_on:
            - link-checker
    link-checker:
        image: identifiersorg/cloud-ws-link-checker
        environment:
            - WS_LINK_CHECKER_CONFIG_REDIS_HOST=redis
            - WS_LINK_CHECKER_CONFIG_REDIS_PORT=6379
            - WS_LINK_CHECKER_CONFIG_BACKEND_SERVICE_RESOLVER_HOST=localhost
            - WS_LINK_CHECKER_CONFIG_DAEMON_PERIODIC_LINK_CHECK_REQUESTER_ENABLED=false
        ports:
            - "8084:8084"
        depends_on:
            - redis
networks:
    default:
        name: idorg-dev-satellite-resolver
volumes:
    registry:
        name: idorg_registry
        external: true