# Development environment for working with the Compact ID Resolution Service

#														#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>	#
#														#
version: "3"
services:
    redis:
        image: redis
        ports:
            - 6379:6379
    recommender:
        image: identifiersorg/cloud-ws-resource-recommender
        ports:
            - 8083:8083
