# Standalone environment for working with the Compact ID Resolution Service

#														#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>	#
#														#
version: "3"
services:
    metadata:
        image: identifiersorg/cloud-ws-resolver
        environment:
            - WS_RESOLVER_CONFIG_REDIS_HOST=redis
            - WS_RESOLVER_CONFIG_REDIS_PORT=6379
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_HOST=recommender
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_PORT=8083
        ports:
            - 8080:8080
        depends_on:
            - redis
    redis:
        image: redis:4.0.8-alpine
        ports:
            - 6379:6379
