# OpenAPI Specification for Identifiers.org Resolution API Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
openapi: 3.0.0
servers:
  - url: 'http://resolver.api.identifiers.org'
    description: Main endpoint for this service
  - url: 'http://resolver.api.gcloud.identifiers.org'
    description: Google Cloud API Service endpoint
  - url: 'http://resolver.api.aws.identifiers.org'
    description: AWS API Service endpoint
info:
  description: Identifiers.org Resolution API Service, for resolution of Compact Identfiiers (preix:id).
    This web service is open source, released under MIT license at [https://github
    .com/identifiers-org/cloud-ws-resolver](GitHub).
    To find out more about Identifiers.org, please, visit our main website at [http://identifiers.org]
    (http://identifiers.org)
  version: "1.0"
  title: Identifiers.org Compact ID Resolution Service
